package HashApp;


/**
* HashApp/Hash.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hash.idl
* Monday, March 16, 2020 12:34:20 AM MMT
*/

public interface Hash extends HashOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hash
