package HashApp;


/**
* HashApp/HashOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hash.idl
* Monday, March 16, 2020 12:34:20 AM MMT
*/

public interface HashOperations 
{
  String add (int meth, String clip);
  void shutdown ();
} // interface HashOperations
