package HashApp;


/**
* HashApp/HashOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hash.idl
* Thursday, February 20, 2020 11:39:29 PM MMT
*/

public interface HashOperations 
{
  String add (int meth, String clip);
  void shutdown ();
} // interface HashOperations
