package HashApp;


/**
* HashApp/Hash.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hash.idl
* Thursday, February 20, 2020 11:39:29 PM MMT
*/

public interface Hash extends HashOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hash
