package HashApp;


/**
* HashApp/HashPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hash.idl
* Thursday, February 20, 2020 11:39:29 PM MMT
*/

public abstract class HashPOA extends org.omg.PortableServer.Servant
 implements HashApp.HashOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HashApp/Hash/add
       {
         int meth = in.read_long ();
         String clip = in.read_string ();
         String $result = null;
         $result = this.add (meth, clip);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HashApp/Hash/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HashApp/Hash:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hash _this() 
  {
    return HashHelper.narrow(
    super._this_object());
  }

  public Hash _this(org.omg.CORBA.ORB orb) 
  {
    return HashHelper.narrow(
    super._this_object(orb));
  }


} // class HashPOA
